In [102]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error
import warnings

warnings.filterwarnings('ignore')

In [103]:
df = pd.read_csv('car data.csv')

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [105]:
df

    Car_Name  Year  Selling_Price  ...  Seller_Type  Transmission Owner
0       ritz  2014           3.35  ...       Dealer        Manual     0
1        sx4  2013           4.75  ...       Dealer        Manual     0
2       ciaz  2017           7.25  ...       Dealer        Manual     0
3    wagon r  2011           2.85  ...       Dealer        Manual     0
4      swift  2014           4.60  ...       Dealer        Manual     0
..       ...   ...            ...  ...          ...           ...   ...
296     city  2016           9.50  ...       Dealer        Manual     0
297     brio  2015           4.00  ...       Dealer        Manual     0
298     city  2009           3.35  ...       Dealer        Manual     0
299     city  2017          11.50  ...       Dealer        Manual     0
300     brio  2016           5.30  ...       Dealer        Manual     0

[301 rows x 9 columns]

In [106]:
df['Seller_Type'].value_counts()

Seller_Type
Dealer        195
Individual    106
Name: count, dtype: int64

In [107]:
df['Car_Name'].value_counts()

Car_Name
city                  26
corolla altis         16
verna                 14
fortuner              11
brio                  10
                      ..
Honda Activa 125       1
Hero Hunk              1
Hero  Ignitor Disc     1
Hero  CBZ Xtreme       1
Bajaj  ct 100          1
Name: count, Length: 98, dtype: int64

In [108]:
df['Transmission'].value_counts()

Transmission
Manual       261
Automatic     40
Name: count, dtype: int64

In [109]:
df['Fuel_Type'] = df['Fuel_Type'].str.lower().str.strip()
df['Seller_Type'] = df['Seller_Type'].str.lower().str.strip()
df['Transmission'] = df['Transmission'].str.lower().str.strip()
df

    Car_Name  Year  Selling_Price  ...  Seller_Type  Transmission Owner
0       ritz  2014           3.35  ...       dealer        manual     0
1        sx4  2013           4.75  ...       dealer        manual     0
2       ciaz  2017           7.25  ...       dealer        manual     0
3    wagon r  2011           2.85  ...       dealer        manual     0
4      swift  2014           4.60  ...       dealer        manual     0
..       ...   ...            ...  ...          ...           ...   ...
296     city  2016           9.50  ...       dealer        manual     0
297     brio  2015           4.00  ...       dealer        manual     0
298     city  2009           3.35  ...       dealer        manual     0
299     city  2017          11.50  ...       dealer        manual     0
300     brio  2016           5.30  ...       dealer        manual     0

[301 rows x 9 columns]

In [110]:
df['Fuel_Type'] = df['Fuel_Type'].map({'petrol' : 0, 'diesel' : 1})
df['Seller_Type'] = df['Seller_Type'].map({'dealer' : 0, 'individual' : 1})
df['Transmission'] = df['Transmission'].map({'manual' : 0, 'automatic' : 1})
df

    Car_Name  Year  Selling_Price  ...  Seller_Type  Transmission  Owner
0       ritz  2014           3.35  ...            0             0      0
1        sx4  2013           4.75  ...            0             0      0
2       ciaz  2017           7.25  ...            0             0      0
3    wagon r  2011           2.85  ...            0             0      0
4      swift  2014           4.60  ...            0             0      0
..       ...   ...            ...  ...          ...           ...    ...
296     city  2016           9.50  ...            0             0      0
297     brio  2015           4.00  ...            0             0      0
298     city  2009           3.35  ...            0             0      0
299     city  2017          11.50  ...            0             0      0
300     brio  2016           5.30  ...            0             0      0

[301 rows x 9 columns]

In [111]:
X = df.drop(['Selling_Price','Car_Name'], axis= 1)
y = df['Selling_Price']

In [112]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           301 non-null    int64
 1   Present_Price  301 non-null    float64
 2   Kms_Driven     301 non-null    int64
 3   Fuel_Type      299 non-null    float64
 4   Seller_Type    301 non-null    int64
 5   Transmission   301 non-null    int64
 6   Owner          301 non-null    int64
dtypes: float64(2), int64(5)
memory usage: 16.6 KB

In [113]:
X['Fuel_Type'].fillna(df['Fuel_Type'].mean(),inplace= True)

In [114]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [115]:
y_test = y_test.astype(int)
X_test = X_test.astype(int)

In [116]:
model = LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

In [117]:
y_pred  = model.predict(X_test)

In [118]:
r2 = r2_score(y_test,y_pred)
r2

0.8317211117993211

In [120]:
mae = mean_absolute_error(y_test,y_pred)
mae

1.3559040380307448